In [1]:
import numpy as np

In [205]:
k = np.array([
    [530, 0, 249],
    [0, 540, 245],
    [0, 0, 1]
])
k

array([[530,   0, 249],
       [  0, 540, 245],
       [  0,   0,   1]])

In [29]:
# R = np.array([
#     [cos(45), 0, -sin(45)],
#     [0, 1, 0],
#     [sin(45), 0, cos(45)]
# ])
# R

In [135]:
k2 = np.array([
    [500, 0, 251],
    [0, 375, 252],
    [0, 0, 1]
])

In [136]:
r2 = np.array([
     [cos(45), 0, -sin(45)],
    [0, 1, 0],
    [sin(45), 0, cos(45)]
])
r2

array([[ 0.70710678,  0.        , -0.70710678],
       [ 0.        ,  1.        ,  0.        ],
       [ 0.70710678,  0.        ,  0.70710678]])

In [187]:
c2 = np.array([[-20, 0, 20]]).T
# c2 = np.array([[-0.20, 0, 0.20]]).T

In [188]:
t2 = (np.dot(r2, -c2))
t2

array([[28.28427125],
       [ 0.        ],
       [ 0.        ]])

In [189]:
rt2 = np.hstack((r2, t2))

In [190]:
rt2

array([[ 0.70710678,  0.        , -0.70710678, 28.28427125],
       [ 0.        ,  1.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.        ,  0.70710678,  0.        ]])

In [191]:
p = np.dot(k2, rt2)
p

array([[ 5.31037193e+02,  0.00000000e+00, -1.76069589e+02,
         1.41421356e+04],
       [ 1.78190909e+02,  3.75000000e+02,  1.78190909e+02,
         0.00000000e+00],
       [ 7.07106781e-01,  0.00000000e+00,  7.07106781e-01,
         0.00000000e+00]])

In [192]:
1 / np.sqrt(2)

0.7071067811865475

In [193]:
def sin(a):
    return np.sin(a * np.pi/180)

In [194]:
def cos(a):
    return np.cos(a * np.pi/180)

In [195]:
X = np.array([[39, 35, 100, 1]]).T
X

array([[ 39],
       [ 35],
       [100],
       [  1]])

In [196]:
p

array([[ 5.31037193e+02,  0.00000000e+00, -1.76069589e+02,
         1.41421356e+04],
       [ 1.78190909e+02,  3.75000000e+02,  1.78190909e+02,
         0.00000000e+00],
       [ 7.07106781e-01,  0.00000000e+00,  7.07106781e-01,
         0.00000000e+00]])

In [197]:
X = X.astype(np.float32)
X

array([[ 39.],
       [ 35.],
       [100.],
       [  1.]], dtype=float32)

In [198]:
x = np.dot(p, X)
x

array([[17245.62728636],
       [37893.5363314 ],
       [   98.28784258]])

In [199]:
np.dot(p[0, :], X)

array([17245.62728636])

In [202]:
(531.037*39-176.07*100+14142.1) / 98.2878

175.45965012951766

In [204]:
x /= x[-1, :]
x

array([[175.46043165],
       [385.53635256],
       [  1.        ]])

In [206]:
k

array([[530,   0, 249],
       [  0, 540, 245],
       [  0,   0,   1]])

In [207]:
r = np.array([
    [1, 0, 0, ],
    [0, 1, 0],
    [0, 0, 1]
])
r

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [208]:
c = np.array([[0, 0, 0]]).T
c

array([[0],
       [0],
       [0]])

In [210]:
t = (np.dot(r, -c))
t

array([[0],
       [0],
       [0]])

In [212]:
rt = np.hstack((r, t))
rt

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [214]:
krt = np.dot(k, rt)
krt

array([[530,   0, 249,   0],
       [  0, 540, 245,   0],
       [  0,   0,   1,   0]])

In [219]:
p = np.array([[38, 40, 100, 1]]).T
p

array([[ 38],
       [ 40],
       [100],
       [  1]])

In [220]:
np.dot(krt, p)

array([[45040],
       [46100],
       [  100]])

In [222]:
kab = (129-79) / (100 - 79)
kab

2.380952380952381

In [224]:
bab = 129 - 100 * kab
bab

-109.0952380952381

In [225]:
a1 = 109.095 - 75.3
b1 = 50/21 - 13 / 9
x1 = a1 / b1

In [226]:
x1

36.08618644067797

In [227]:
50/21 * x1 - 109.095

-23.17550847457626

In [228]:
13/9 * x1 - 75.3

-23.17550847457626