In [33]:
import numpy as np
# import matplotlib.pyplot as plt

In [42]:
def c(T, Xs, thr=0.00000000000001):
    res = []
    n = T.shape[0]
    for x0 in Xs:
        x1 = np.dot(T.T, x0)
        diff = np.square((x1 - x0)).sum()
        while diff > thr:
            x0 = x1
            x1 = np.dot(T.T, x1)
            diff = np.square((x1 - x0)).sum()
        res.append(x1)
    return np.around(res, 5)

In [43]:
a = 1/2
b = 1/4


In [44]:
arr = np.array([
    [a, 0, b, 0, 0, 0, 0, b],
    [0, 0, b, 0, 0, b, 0, a],
    [b, 0, a, 0, 0, 0, b, 0],
    [0, 0, 0, a, 0, b, 0, b],
    [b, 0, 0, b, 0, 0, a, 0],
    [0, 0, 0, b, 0, a, b, 0],
    [0, 0, 0, 0, 0, 0, 1, 0],
    [1/6, 1/6, 1/6, 1/6, 1/6, 1/6, 0, 0]
])

In [45]:
arr.sum(axis=1)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
Xs = [
    np.array([[1, 0, 0, 0, 0, 0, 0, 0]]).T,
    np.array([[0, 1, 0, 0, 0, 0, 0, 0]]).T,
    np.array([[0, 0, 1, 0, 0, 0, 0, 0]]).T,
    np.array([[0, 0, 0, 1, 0, 0, 0, 0]]).T,
    np.array([[0, 0, 0, 0, 1, 0, 0, 0]]).T,
    np.array([[0, 0, 0, 0, 0, 1, 0, 0]]).T,
    np.array([[0, 0, 0, 0, 0, 0, 1, 0]]).T,
    np.array([[0, 0, 0, 0, 0, 0, 0, 1]]).T
]

In [47]:
res = c(arr, Xs, 0.1 ** 15)

In [48]:
res

array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.]]])

In [49]:
def d(v, n, T):
    res = v
    for i in range(n):
        res = np.dot(T.T, res)
    return res

In [50]:
initial = np.array([[0, 0, 0, 0, 0, 0, 0, 1]]).T
initial

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1]])

In [51]:
res = d(initial, 10, arr)
res

array([[0.0652284 ],
       [0.00776264],
       [0.0652284 ],
       [0.0652284 ],
       [0.00776264],
       [0.0652284 ],
       [0.68232476],
       [0.04123634]])

In [52]:
res.sum()

0.9999999999999998

In [53]:
# v: initial state vector
# i: the ith state
# T: transition matrix
# thr: threshold to reach
def e(v, i, T, thr):
    n = 0
    p = v[i - 1][0]
    while p < thr:
        v = np.dot(T.T, v)
#         print(v)
        p = v[i - 1][0]
        n += 1
#         print(p, "\n")
    return n

In [54]:
res = e(initial, 7, arr.copy(), 0.95)
res

26

In [55]:
# arr = np.array([
#     [a, 0, b, 0, b, 0, 0, a],
#     [0, a, b, 0, 0, b, 0, a],
#     [b, b, a, 0, 0, 0, a, 0],
#     [0, 0, 0, a, b, b, 0, a],
#     [b, 0, 0, b, a, 0, a, 0],
#     [0, b, 0, b, 0, a, a, 0],
#     [0, 0, 0, 0, 0, 0, 1, 0],
#     [b, b, b, b, b, b, 0, 0]
# ])
# arr

In [67]:
def f(T, i):
    Q = np.delete(T, i - 1, axis=1)
    Q = np.delete(Q, i - 1, axis=0)
    I = np.identity(Q.shape[0])
    N = np.linalg.inv(I - Q)
    print(N.sum(axis=0))
    res = np.sum(N, axis=0)[-1]
    return res
    

In [68]:
res = f(arr.copy(), 7)
res

[11.66666667  2.33333333 11.66666667 11.66666667  2.33333333 11.66666667
  8.        ]


8.0

In [58]:
arr

array([[0.5       , 0.        , 0.25      , 0.        , 0.        ,
        0.        , 0.        , 0.25      ],
       [0.        , 0.        , 0.25      , 0.        , 0.        ,
        0.25      , 0.        , 0.5       ],
       [0.25      , 0.        , 0.5       , 0.        , 0.        ,
        0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.5       , 0.        ,
        0.25      , 0.        , 0.25      ],
       [0.25      , 0.        , 0.        , 0.25      , 0.        ,
        0.        , 0.5       , 0.        ],
       [0.        , 0.        , 0.        , 0.25      , 0.        ,
        0.5       , 0.25      , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        ],
       [0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
        0.16666667, 0.        , 0.        ]])

In [59]:
res = d(initial, 8, arr.copy())
res

array([[0.08325949],
       [0.00989222],
       [0.08325949],
       [0.08325949],
       [0.00989222],
       [0.08325949],
       [0.59451256],
       [0.05266505]])

In [60]:
initial

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1]])